### ISSUE TITLE
Uncaught TypeError in jquery.multiselect.js:1761

### ISSUE THREAD

**Issue by JoeZhou266** [lou/multi-select#312]
Hi supporter,

Hope you are doing well. I got some error in jquery.multiselect.js when I upgrade JQuery from version 1 to 3.3.1. Could you give some advice. Thank you so much.
jquery.multiselect.js:1761 Uncaught TypeError: data[option] is not a function
    at HTMLSelectElement.<anonymous> (jquery.multiselect.js:1761)
    at Function.each (jquery-3.3.1.js:354)
    at jQuery.fn.init.each (jquery-3.3.1.js:189)
    at jQuery.fn.init.$.fn.multiselect (jquery.multiselect.js:1749)
    at HTMLSelectElement.filterUpdateStrains (Strain.js:78)
    at HTMLSelectElement.dispatch (jquery-3.3.1.js:5183)
    at HTMLSelectElement.elemData.handle (jquery-3.3.1.js:4991)
    at Object.trigger (jquery-3.3.1.js:8249)
    at HTMLSelectElement.<anonymous> (jquery-3.3.1.js:8327)
    at Function.each (jquery-3.3.1.js:354)
